name: Daily CC-NEWS

on:
  workflow_dispatch:
    inputs:
      date_range:
        description: Allowed article date range (pair of dates)
        default: 'yesterday'
        required: true
      cohort_count:
        description: Count of cohorts to process (integer)
        default: 5
        required: true
        type: number
      cohorts:
        description: Cohorts to process (JSON list of integers)
        default: '[0, 1, 2, 3, 4]'
        required: true
  schedule:
  - cron: '30 5 * * *'

run-name: CC-NEWS ${{ inputs.date_range || 'yesterday' }}

jobs:

  ccdl:
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        cohort: ${{ fromJSON(inputs.cohorts) }}
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_PAT }}
    outputs:
      DATE_RANGE: ${{ steps.main.outputs.DATE_RANGE }}
    name: CC-NEWS ${{ inputs.date_range || 'yesterday' }}-C${{ matrix.cohort }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: Fox-Tango/ccnews
        token: ${{ secrets.GH_PAT }}
    - name: Install prerequisites
      run: |
        pip install -r tools/requirements.txt
    - name: Process CC-NEWS ${{ inputs.date_range || 'yesterday' }}-C${{ matrix.cohort }}
      id: main
      run: |
        date_range="${{ inputs.date_range || 'yesterday' }}"
        if [[ "$date_range" == "yesterday" ]]; then
          y=$(date -d "yesterday" '+%Y-%m-%d')
          date_range="$y,$y"
        fi
        echo DATE_RANGE=$date_range >>$GITHUB_OUTPUT
        if tools/sp500.py srcdata; then
          tools/sp500-filter.py srcdata
        fi
        tools/ccdl.py --url-filter=@srcdata/url-filter.txt --lang-filter=en --cats-filter=economy --term-filter=@srcdata/sp500-filter.txt --date-range="$date_range" --warc-date-range="$date_range" --warc-cohort=${{ matrix.cohort }},${{ inputs.cohort_count }} ccnews-${{ inputs.date_range || 'yesterday' }}-C${{ matrix.cohort }}.sqlite
    - name: Upload partial database
      uses: actions/upload-artifact@v3
      with:
        name: partial
        path: ccnews-${{ inputs.date_range || 'yesterday' }}-C${{ matrix.cohort }}.sqlite

  release:
    needs: ccdl
    if: always()
    runs-on: ubuntu-latest
    env:
      DATE_RANGE: ${{ needs.ccdl.outputs.DATE_RANGE }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: Fox-Tango/ccnews
        token: ${{ secrets.GH_PAT }}
    - name: Install prerequisites
      run: |
        pip install -r tools/requirements.txt
    - name: Download partial databases
      uses: actions/download-artifact@v3
      with:
        name: partial
    - name: Merge partial databases
      run: |
        tools/mergedb.py --table=ccindex,files ccnews-*.sqlite ccnews.sqlite
        tools/cc2csv.py ccnews.sqlite daily
    - name: Upload merged database
      uses: actions/upload-artifact@v3
      with:
        name: merged
        path: ccnews.sqlite
    - name: Upload sentiment data
      uses: actions/upload-artifact@v3
      with:
        name: daily+${{ env.DATE_RANGE }}
        path: daily/

  keepalive:
    needs: release
    if: always()
    permissions:
      actions: write
    steps:
    - name: Keep workflow alive
      run: |
        WORKFLOW="${{ github.workflow_ref }}"
        WORKFLOW="${WORKFLOW%@*}"
        WORKFLOW="${WORKFLOW##*/}"
        gh api -X PUT repos/${{ github.repository }}/actions/workflows/$WORKFLOW/enable
